updated metadata display
ComPlat/chemotion-converter-client pull request #76
Opened 2024-12-04 13:41 UTC by headri

no line breaks in key and show tooltip if key too long

2024-12-11 11:51 UTC, StarmanMartin requested changes
Would be nice if you could fix the one comment, thanks.

2024-12-11 11:51 UTC, StarmanMartin commented on src/js/components/admin/form/ProfileForm.js
> +      <style type="text/css">
Style tag should not be in the html body. It should be in the head instead. Especially if the css part is static and does not have to be changed in the React element dynamically

2025-01-09 13:05 UTC, StarmanMartin approved these changes

2025-01-09 13:56 UTC, PiTrem requested changes

2025-01-09 13:56 UTC, PiTrem commented on src/js/components/admin/form/ProfileForm.js
> +                <Col as="dt" lg={5}><div class='div-nowrap'>{key}:</div></Col>
`className` not `class` ?

2025-01-09 13:56 UTC, PiTrem commented on src/js/components/admin/form/ProfileForm.js
> +              {key.length > window.innerWidth / 50 ? (  // only show tooltip if key is long (compared on window size)
can the use of window be avoided? 
the component is not aware if the window is being resized and I don't think  this is so critical to warrant adding more logic for a listener either.
 Why not have the tooltip in any cases
Otherwise use a reference (useRef) to check the properties scrollWidth and offsetWidth.

2025-01-17 14:29 UTC, PiTrem approved these changes

2025-01-17 14:34 UTC, merged